# For more information: https://laravel.com/docs/sail
version: '3.9'
services:
    laravel:
        container_name: laravel
        image: docker.io/bitnami/laravel:9
        ports:
            - '${BACKEND_PORT}:8000'
        env_file:
            - .env
        environment:
            APP_URL: http://localhost:${BACKEND_PORT}
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
        volumes:
            - './backend:/app'
        networks:
            - default
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT_FORWARD}:3306'
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - default
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    react:
        container_name: frontend
        working_dir: /app
        image: 'node:16.15-alpine'
        command: yarn run dev
        depends_on:
            - laravel
        env_file:
            - .env
        ports:
            - "${FRONTEND_PORT}:3000"
        environment:
            - NODE_ENV=development
        volumes:
            - ./frontend:/app
networks:
    default:
        driver: bridge
volumes:
    mysql:
        driver: local